Repository charmplusplus/charm, pull requests merged in 2019-10, with the labels that each got.

#2553 cmake: clarify why we need 3.11
  CMakeLists.txt
Labels: Build & test automation

#2557 cmake: add conv-static dependency to romio
  src/libs/ck-libs/ampi/CMakeLists.txt
Labels: Build & test automation

#2560 remove ccache from travis ci Mac build
  .travis.yml
Labels: Build & test automation

#2540 bugfix (#1485): fix charmdebug breakpoints in SMP mode
  src/arch/netlrts/machine.C
  src/ck-core/debug-charm.C
  src/ck-core/init.C
  src/ck-core/register.C
  src/ck-core/register.h
  src/conv-ccs/ccs-server.C
  src/conv-ccs/conv-ccs.C
  src/conv-ccs/middle-ccs.C
  src/conv-core/convcore.C
Labels: Bug, CharmDebug

#2567 Bug #2495: remove -isysroot from charmc arguments
  src/scripts/charmc
Labels: CMake

#2568 cmake: lower version requirement and fix Fortran linking
  CHANGES
  CMakeLists.txt
  doc/charm++/manual.rst
Labels: CMake

#2562 UCX: Several fixes
  src/arch/ucx/machine.C
Labels: UCX

#2581 HAPI: Remove dependency on Charm++ layer and fix WorkRequest instrumentation
  src/arch/cuda/hybridAPI/hapi_impl.cpp
  src/ck-core/ck.C
  src/ck-core/init.C
Labels: GPU support

#2586 HAPI: Remove redundant CMK_MULTICORE, replace printf with CmiPrintf
  src/arch/cuda/hybridAPI/hapi_impl.cpp
Labels: GPU support

#2584 cmake: fall back to ./build when cmake too old/nonexistent
  CMakeLists.txt
  buildcmake
Labels: CMake
