Repository charmplusplus/charm, pull requests merged in 2019-12, with the labels that each got.

#2621 charmc #2617: pass through rsp files
  src/scripts/charmc
Labels: charmc

#2626 HAPI: Fix mempool creation
  src/arch/cuda/hybridAPI/hapi_impl.cpp
Labels: Bug, GPU support

#2641 ckCheckpoint: create subdirectories for nodegroup files, if needed.
  src/ck-core/ckcheckpoint.C
Labels: checkpoint/restart

#2645 Checkpoint: use str() instead of rdbuf() to copy dirPath.
  src/ck-core/ckcheckpoint.C
Labels: checkpoint/restart

#2656 AMPI #2655: hide MPI_COMM constant from public Fortran header
  src/libs/ck-libs/ampi/ampif.h
Labels: AMPI

#2653 Fix missing CmiInCommThread
  src/conv-core/converse.h
Labels: smp

#2651 HAPI: Update build script to first use NVCC path to set CUDA directory
  build
Labels: GPU support

#2658 Cleanup: Replace CmmTable with std::map in CPU affinity and topology
  src/conv-core/cpuaffinity.C
  src/conv-core/cputopology.C
  src/util/sockRoutines.h
Labels: cleanup

#2659 Support logical PU indices in +pemap and +commap
  doc/charm++/manual.rst
  src/conv-core/cpuaffinity.C
Labels: provisioning

#2642 HAPI: Add +gpumap and +allgpus options for PE-GPU mapping
  examples/charm++/cuda/hello/hello.C
  src/arch/cuda/hybridAPI/hapi_impl.cpp
  src/arch/cuda/hybridAPI/hapi_impl.h
  src/ck-core/init.C
Labels: GPU support
