Repository charmplusplus/charm, pull requests merged in 2019-06, with the labels that each got.

#2284 Doc: Add quickstart
  doc/charm++/manual.rst
  doc/index.rst
  doc/quickstart.rst
Labels: documentation

#2282 AMPI: Fail compilation when unable to get binary path
  src/libs/ck-libs/ampi/ampi.C
Labels: AMPI

#2281 fix #2268: undefined CthScheduled
  src/conv-core/threads.C
Labels: bug, openmp integration

#2302 bugfix (#1473) : fix ancient ordering bug in benchmark
  benchmarks/charm++/communication_overhead/overhead_test.C
Labels: bug, machine layers

#2139 add OpenMP offloading example
  examples/charm++/shared_runtimes/openmp-offload/vecadd/Makefile
  examples/charm++/shared_runtimes/openmp-offload/vecadd/README
  examples/charm++/shared_runtimes/openmp-offload/vecadd/vecadd.C
  examples/charm++/shared_runtimes/openmp-offload/vecadd/vecadd.ci
Labels: GPU support

#2306 cleanup #2034: remove mlog and causalft
  README.md
  build
  smart-build.pl
  src/arch/common/conv-mach-causalft.h
  src/arch/common/conv-mach-causalft.sh
  src/arch/common/conv-mach-mlogft.h
  src/arch/common/conv-mach-mlogft.sh
  src/arch/util/immediate.C
  src/ck-core/charm++.h
  src/ck-core/charm.h
  src/ck-core/ck.C
  src/ck-core/ckarray.C
  src/ck-core/ckarray.h
  src/ck-core/ckcausalmlog.C
  src/ck-core/ckcausalmlog.h
  src/ck-core/ckcheckpoint.C
  src/ck-core/ckcheckpoint.h
  src/ck-core/cklocation.C
  src/ck-core/cklocation.h
  src/ck-core/cklocrec.h
  src/ck-core/ckmessagelogging.C
  src/ck-core/ckmessagelogging.h
  src/ck-core/ckmulticast.C
  src/ck-core/ckreduction.C
  src/ck-core/ckreduction.h
  src/ck-core/envelope.h
  src/ck-core/init.C
  src/ck-ldb/BaseLB.h
  src/ck-ldb/CentralLB.C
  src/ck-ldb/CentralLB.h
  src/ck-ldb/LBDBManager.h
  src/conv-core/msgmgr.C
  src/libs/ck-libs/ampi/ampi.C
  src/scripts/Make.depends
  src/scripts/Makefile
  src/util/charmrun-src/charmrun.C
  src/util/ckhashtable.h
  src/util/ckregex.h
  tests/Makefile
  tests/ampi/Makefile
  tests/ampi/jacobi3d/Makefile
  tests/charm++/Makefile
  tests/charm++/jacobi3d-gausssiedel/Makefile
  tests/charm++/jacobi3d-sdag/Makefile
  tests/charm++/jacobi3d/Makefile
Labels: cleanup, fault tolerance

#2265 Bug #2059: Apply +pemap and +commap in terms of hwloc PUs
  src/conv-core/converse.h
  src/conv-core/cpuaffinity.C
  src/conv-core/cputopology.C
Labels: provisioning

#2337 add circleci integration
  .circleci/config.yml
Labels: Build & test automation

#2338 AMPI: fix MPI_Info_dup to actually copy over keyval pairs
  src/libs/ck-libs/ampi/ampiMisc.C
Labels: AMPI

#2305 AMPI: fix CUDA builds and the AMPI+CUDA example's Makefile
  examples/ampi/cuda/simple/Makefile
  src/libs/ck-libs/ampi/ampi.C
  src/libs/ck-libs/ampi/ampiimpl.h
Labels: AMPI, GPU support

#2362 Propagate main()'s return code in AMPI
  src/libs/ck-libs/ampi/ampi.C
  src/libs/ck-libs/ampi/ampi.h
  src/libs/ck-libs/ampi/compat_ampi.c
Labels: AMPI
