Repository charmplusplus/charm, pull requests merged in 2019-09, with the labels that each got.

#2501 Armv8 does not build with UCX
  doc/charm++/manual.rst
  src/arch/ucx-linux-arm8/conv-mach-ompipmix.h
  src/arch/ucx-linux-arm8/conv-mach-ompipmix.sh
  src/arch/ucx-linux-arm8/conv-mach-slurmpmi.h
  src/arch/ucx-linux-arm8/conv-mach-slurmpmi.sh
  src/arch/ucx-linux-arm8/conv-mach-slurmpmi2.h
  src/arch/ucx-linux-arm8/conv-mach-slurmpmi2.sh
  src/arch/ucx-linux-arm8/conv-mach-smp.h
  src/arch/ucx-linux-arm8/conv-mach-smp.sh
  src/arch/ucx-linux-arm8/conv-mach.h
  src/arch/ucx-linux-arm8/conv-mach.sh
Labels: UCX

#2519 quickstart: point URL to latest release
  doc/quickstart.rst
Labels: documentation

#2517 Revert synchronous memory copy operations in GPU Manager to be truly asynchronous
  src/arch/cuda/hybridAPI/hapi.h
  src/arch/cuda/hybridAPI/hapi_impl.cpp
Labels: GPU support, Performance

#2535 cmake: fix replaysystem spelling
  CMakeLists.txt
Labels: Build & test automation

#2208 CHANGES: add release notes for v6.10.0
  CHANGES
Labels: documentation

#2533 Add CMake build to GitHub CI
  .github/workflows/cmake.yml
Labels: Build & test automation

#2543 Manual: cleanups
  doc/charm++/manual.rst
Labels: documentation

#2538 Add documentation for building and running Charm programs with UCX backend
  README.md
  doc/charm++/manual.rst
Labels: documentation

#2537 AMPI Benchmarks: Make pingpong run on a range of message sizes
  benchmarks/ampi/pingpong/Makefile
  benchmarks/ampi/pingpong/pingpong-1way.c
Labels: AMPI
