Repository charmplusplus/charm, pull requests merged in 2020-01, with the labels that each got.

#2666 LBDB: fix CMK_LBDB_ON #ifdef
  src/ck-ldb/LBDatabase.C
Labels: load balancing

#2667 HAPI: Perform setup and device mapping only on worker threads
  src/ck-core/init.C
  src/conv-core/convcore.C
Labels: GPU support

#2668 LBDB: fix more undefined symbols
  src/ck-ldb/LBDatabase.C
  src/conv-core/convcore.C
Labels: load balancing

#2669 CI: Add UTH test
  .github/workflows/uth.yml
Labels: Build & test automation

#2664 Bug #2647: Improve +setcpuaffinity defaults
  src/conv-core/cpuaffinity.C
Labels: provisioning

#2670 jacobi: do not use VLA
  tests/charm++/jacobi3d-sdag/jacobi3d.C
  tests/charm++/jacobi3d/jacobi3d.C
Labels: Build & test automation

#2675 charmrun: fix syntax error in mpi win
  src/arch/mpi-win64/charmrun
Labels: Windows, charmrun

#2288 Travis: add windows CI
  .travis.yml
  src/arch/win/travis.sh
  src/arch/win/unix2nt_cc
  src/libs/ck-libs/metis/GKlib/Makefile
  src/libs/ck-libs/metis/GKlib/gk_arch.h
  src/libs/ck-libs/metis/GKlib/gk_getopt.h
  src/util/charmrun-src/charmrun.C
  tests/charm++/megatest/immediatering.C
Labels: Build & test automation, Windows

#2587 CDash Integration
  README.md
  cdash/.gitignore
  cdash/CTestConfig.cmake
  cdash/CTestCustom.cmake
  cdash/CTestTestfile.cmake
  cdash/Init.cmake
  cdash/Stages.cmake
  cdash/Utilities.cmake
  cdash/generate_ctest.py
  cdash/run_autobuild.sh
Labels: Build & test automation

#2682 GitHub CI: limit jobs to 45 minutes
  .github/workflows/bigsim.yml
  .github/workflows/cmake.yml
  .github/workflows/uth.yml
  .github/workflows/verbs.yml
Labels: Build & test automation

#2683 GitHub CI: add UCX build
  .github/workflows/ucx.yml
Labels: Build & test automation

#2684 Cdash: set default branch to 'master'
  cdash/run_autobuild.sh
Labels: Build & test automation

#2687 uth: use gfortran
  src/arch/uth-linux-x86_64/conv-mach.sh
  src/arch/uth-linux/conv-mach.sh
Labels: UTH

#2690 uth: skip tlsglobals test
  examples/ampi/Cjacobi3D/Makefile
Labels: UTH

#2691 bigsim-examples: fix path to conv-mach-opt.mak
  examples/bigsim/Makefile
Labels: BigSim
