Repository charmplusplus/charm, pull requests merged in 2020-12, with the labels that each got.

#3172 CMake: Let child Make instances see parent jobserver
  CMakeLists.txt
  cmake/hwloc.cmake
  src/libs/ck-libs/ampi/CMakeLists.txt
Labels: CMake

#3177 CI: enable checks from forks and fix Spack CI
  .github/workflows/buildold.yml
  .github/workflows/changa.yml
  .github/workflows/charm4py.yml
  .github/workflows/cuda.yml
  .github/workflows/multicore_darwin.yml
  .github/workflows/namd.yml
  .github/workflows/shellcheck.yml
  .github/workflows/spack.yml
  .github/workflows/ucx.yml
  .github/workflows/verbs.yml
Labels: CI

#3182 CI: Move NetLRTS Darwin and MPI Linux SMP to GitHub
  .github/workflows/mpi_linux_smp.yml
  .github/workflows/netlrts_darwin.yml
  .travis.yml
Labels: CI

#3183 Tracing: Add username to Projections logs
  src/ck-perf/trace-common.C
Labels: enhancement, tracing

#3184 CMake: Fix build on ARM platforms
  CMakeLists.txt
  cmake/detect-features-c.cmake
  cmake/hwloc.cmake
  src/util/boost-context/CMakeLists.txt
Labels: CMake

#3187 Update .clang-format: Indent preprocessor directives
  .clang-format
Labels: formatting

#3188 Use Winsock2.h instead of deprecated winsock.h in ntohl check
  src/conv-core/debug-conv.C
  src/scripts/configure.ac
Labels: Windows

#3192 Configure: Remove unnecessary gethostname() test
  cmake/detect-features-c.cmake
  src/conv-core/cpuaffinity.C
  src/conv-core/cputopology.C
  src/scripts/configure.ac
Labels: cleanup

#3194 Add OpenPMIx for OFI and UCX machine layers
  .github/workflows/ucx.yml
  CMakeLists.txt
  buildcmake
  doc/charm++/manual.rst
  smart-build.pl
  src/arch/ofi/conv-mach-openpmix.h
  src/arch/ofi/conv-mach-openpmix.sh
  src/arch/ucx/conv-mach-openpmix.h
  src/arch/ucx/conv-mach-openpmix.sh
Labels: OFI, UCX

#3198 PUP: Use std::is_base_of for recursive pup
  src/ck-core/charm++.h
Labels: cleanup

#3197 Use perfect forwarding to pass args to chare's parent constructor
  src/ck-core/charm++.h
Labels: cleanup, enhancement

#3165 Use CkSyncBarrier directly and cleanup usage sites
  src/ck-core/cklocation.C
  src/ck-core/cklocation.ci
  src/ck-core/cklocation.h
  src/ck-core/cklocrec.h
  src/ck-ldb/LBDatabase.C
  src/ck-ldb/LBDatabase.h
  src/ck-ldb/LBManager.C
  src/ck-ldb/LBManager.h
Labels: cleanup

#3190 Clean up compiler warnings
  CMakeLists.txt
  benchmarks/ampi/alltoall/allgather.c
  benchmarks/ampi/alltoall/alltoall.c
  benchmarks/ampi/alltoall/alltoall_VPtest.c
  benchmarks/converse/commbench/pingpong-cachemiss.c
  cmake/Makefile.tests
  cmake/Makefile.tests.common
  examples/charm++/load_balancing/stencil3d/stencil3d.C
  examples/charm++/zerocopy/entry_method_api/prereg/stencil3d/stencil3d.C
  examples/charm++/zerocopy/entry_method_api/reg/stencil3d/stencil3d.C
  examples/charm++/zerocopy/entry_method_api/unreg/stencil3d/stencil3d.C
  src/arch/win/unix2nt_cc
  src/ck-core/ckrdma.C
  src/ck-ldb/LBManager.C
  src/ck-ldb/TreeLevel.h
  src/conv-ccs/middle-ccs.C
  src/conv-core/cpuaffinity.C
  src/conv-core/debug-conv.C
  src/libs/ck-libs/ampi/CMakeLists.txt
  src/libs/ck-libs/metis/GKlib/gk_arch.h
  src/libs/ck-libs/metis/GKlib/gkregex.c
  src/libs/ck-libs/metis/libmetis/metis.h
  src/scripts/Makefile
  src/scripts/configure.ac
  src/util/charmrun-src/charmrun.C
  tests/charm++/load_balancing/lb_test/Topo.C
  tests/charm++/load_balancing/lb_test/lb_test.C
  tests/charm++/method_templates/Makefile
Labels: cleanup

#3209 CI: Add ppc64le build to Travis
  .travis.yml
Labels: CI

#3211 Fix USER_OPTS_LD in conv-mach-pre.sh
  buildcmake
Labels: CMake

#3220 PUP: Add support for std::chrono::{duration, time_point}
  src/util/pup_stl.h
Labels: enhancement

#3221 Tracing: Consume gz flags properly and correct documentation
  doc/charm++/manual.rst
  doc/projections/manual.rst
  src/ck-perf/trace-projections.C
Labels: documentation, tracing
