Repository charmplusplus/charm, pull requests merged in 2021-11, with the labels that each got.

#3521 doc: fix readthedocs build
  doc/.requirements
  doc/requirements.txt
Labels: documentation

#3525 Fix charmxi issue with GPU messaging path
  src/xlat-i/xi-Entry.C
Labels: charmxi, GPU support

#3523 Tracing: Use vector for Projections LogPool
  src/ck-perf/trace-projections.C
  src/ck-perf/trace-projections.h
Labels: cleanup, tracing
