Repository charmplusplus/charm, pull requests merged in 2021-01, with the labels that each got.

#3217 CI: Classify external code as "library" for lgtm
  .lgtm.yml
Labels: Build & test automation, CI

#3191 Tracing: Trace nested events by default
  doc/charm++/manual.rst
  doc/projections/manual.rst
  src/ck-perf/trace-projections.C
Labels: tracing

#3234 icc: Fix broken hwloc configure
  src/arch/common/cc-icc.sh
Labels: Bug

#3232 fixup! CI: Classify external code as "library" for lgtm (#3217)
  .lgtm.yml
Labels: Build & test automation, CI

#3240 Add CMK_DEPRECATED{_MSG} macro
  src/conv-core/converse.h
Labels: enhancement

#3239 cmake: honor $OPTS for ci files
  cmake/ci-files.cmake
Labels: CMake

#3196 Documentation: Refactor AMPI manual section on privatization methods
  .travis.yml
  doc/ampi/figs/global.png
  doc/ampi/manual.rst
Labels: AMPI, documentation

#3214 LB: Don't show CentralLB in help message
  src/ck-ldb/CentralLB.C
Labels: ease of use, load balancing

#3241 LB: Add rule for building ScotchLB in CMake build
  src/ck-core/CMakeLists.txt
Labels: CMake, load balancing

#3225 Tracing: Write SMPMODE even when comm thread tracing is disabled
  src/ck-perf/trace-common.C
  src/ck-perf/trace-projections.h
Labels: smp, tracing

#3229 Update .clang-format: Never allow single line if statements
  .clang-format
Labels: formatting

#3242 cmake: warn about running make in tmp
  cmake/Makefile.tests
Labels: CMake

#3256 AMPI: split doc into multiple files
  doc/ampi/01-introduction.rst
  doc/ampi/02-building.rst
  doc/ampi/03-using.rst
  doc/ampi/04-extensions.rst
  doc/ampi/05-examples.rst
  doc/ampi/manual.rst
Labels: AMPI, documentation

#3255 Fix Fortran Attribute Getters for AMPI Built-ins
  src/libs/ck-libs/ampi/ampif.C
Labels: AMPI

#3264 CI: Update NAMD build to use new GitLab repo
  .github/workflows/namd.yml
Labels: CI

#3213 LB: Build all available LBs by default
  src/ck-core/CMakeLists.txt
  src/ck-ldb/CommonLBs.ci
  src/ck-ldb/Make.lb
  src/ck-ldb/Makefile_lb.sh
  src/ck-ldb/libmoduleCommonLBs.dep
Labels: ease of use, load balancing

#3101 Persistent Intra-node GPU Messaging
  benchmarks/charm++/cuda/gpudirect/Makefile
  benchmarks/charm++/cuda/gpudirect/latency-persistent/Makefile
  benchmarks/charm++/cuda/gpudirect/latency-persistent/latency.C
  benchmarks/charm++/cuda/gpudirect/latency-persistent/latency.ci
  doc/charm++/manual.rst
  examples/charm++/cuda/gpudirect/jacobi3d/jacobi3d.C
  examples/charm++/cuda/gpudirect/jacobi3d/jacobi3d.ci
  examples/charm++/cuda/gpudirect/jacobi3d/jacobi3d.cu
  examples/charm++/cuda/gpudirect/jacobi3d/jacobi3d.h
  examples/charm++/cuda/gpudirect/persistent/Makefile
  examples/charm++/cuda/gpudirect/persistent/persistent.C
  examples/charm++/cuda/gpudirect/persistent/persistent.ci
  examples/charm++/cuda/gpudirect/persistent/persistent.cu
  src/arch/cuda/hybridAPI/hapi.h
  src/arch/cuda/hybridAPI/hapi_functions.h
  src/arch/cuda/hybridAPI/hapi_impl.cpp
  src/ck-core/ckrdmadevice.C
  src/ck-core/ckrdmadevice.h
  src/conv-core/conv-rdmadevice.C
  src/conv-core/conv-rdmadevice.h
  src/libs/ck-libs/ampi/ampi.C
  src/libs/ck-libs/ampi/ampi.h
Labels: GPU support

#3268 Fix semantic of getting AMPI-specific attributes to match standard ones
  doc/ampi/04-extensions.rst
  src/libs/ck-libs/ampi/ampi.C
  src/libs/ck-libs/ampi/ampif.C
  tests/ampi/megampi/test.C
  tests/ampi/privatization/test.C
Labels: AMPI

#3267 Remove CMK_FAULT_EVAC
  doc/ampi/04-extensions.rst
  src/arch/netlrts/machine.C
  src/arch/verbs/machine.C
  src/ck-core/CMakeLists.txt
  src/ck-core/charm++.h
  src/ck-core/ck.C
  src/ck-core/ckarray.C
  src/ck-core/ckarray.h
  src/ck-core/ckevacuation.C
  src/ck-core/ckevacuation.h
  src/ck-core/cklocation.C
  src/ck-core/cklocation.h
  src/ck-core/cklocrec.h
  src/ck-core/ckmigratable.h
  src/ck-core/ckreduction.C
  src/ck-core/ckreduction.ci
  src/ck-core/ckreduction.h
  src/ck-core/init.C
  src/ck-ldb/CentralLB.C
  src/conv-core/convcore.C
  src/conv-core/converse.h
  src/conv-core/threads.C
  src/libs/ck-libs/NDMeshStreamer/Make.depends
  src/libs/ck-libs/ampi/ampi.C
  src/libs/ck-libs/ampi/ampi_functions.h
  src/libs/ck-libs/ampi/ampif.C
  src/libs/ck-libs/ckloop/Make.depends
  src/libs/ck-libs/completion/Make.depends
  src/libs/ck-libs/pose/Make.depends
  src/libs/ck-libs/tcharm/tcharm.C
  src/libs/ck-libs/tcharm/tcharm_impl.h
  src/libs/ck-libs/tcharm/tcharmc.h
  src/scripts/Make.depends
  src/scripts/Makefile
Labels: cleanup
