Repository charmplusplus/charm, pull requests merged in 2022-10, with the labels that each got.

#3648 Tracing: Remove erroneous parameter in summary data collection function
  src/ck-perf/trace-summaryBOC.h
Labels: Bug, tracing

#3651 LB: Respect ++quiet when printing LB comm disabled message
  src/ck-ldb/LBManager.C
Labels: Bug, load balancing

#3658 Use dynamic_cast in unique_ptr serialization
  src/util/pup_stl.h
Labels: Bug, enhancement
