Repository charmplusplus/charm, pull requests merged in 2023-07, with the labels that each got.

#3745 Add Contributing section to README
  README.md
Labels: documentation

#3752 CI: Limit charm4py Cython version
  .github/workflows/charm4py.yml
Labels: CI

#3756 hapiMapping(): handle PEs not a multiple of GPUs.
  src/arch/cuda/hybridAPI/hapi_impl.cpp
Labels: GPU support

#3754 HAPI createPool() and releasePool(): save chunk addresses for cudaFreeHost()
  src/arch/cuda/hybridAPI/hapi_impl.cpp
  src/arch/cuda/hybridAPI/hapi_impl.h
Labels: GPU support
